# Generated by Django 2.1.7 on 2019-05-19 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import utils.django.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Fecha de actualizacion', null=True)),
                ('deleted_date', models.DateTimeField(help_text='Fecha de eliminacion', null=True)),
                ('state', django_enumfield.db.fields.EnumField(default=1, enum=utils.django.db.models.State)),
                ('created_by', models.ForeignKey(help_text='Usuario que crea el objeto', on_delete=django.db.models.deletion.CASCADE, related_name='availableproduct_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Fecha de actualizacion', null=True)),
                ('deleted_date', models.DateTimeField(help_text='Fecha de eliminacion', null=True)),
                ('state', django_enumfield.db.fields.EnumField(default=1, enum=utils.django.db.models.State)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_by', models.ForeignKey(help_text='Usuario que crea el objeto', on_delete=django.db.models.deletion.CASCADE, related_name='customer_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(help_text='Usuario que elimina el objeto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Usuario que actualiza el objeto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Fecha de actualizacion', null=True)),
                ('deleted_date', models.DateTimeField(help_text='Fecha de eliminacion', null=True)),
                ('state', django_enumfield.db.fields.EnumField(default=1, enum=utils.django.db.models.State)),
                ('delivery_address', models.CharField(help_text='customer delivery address', max_length=100)),
                ('date', models.DateField(help_text='date order processing')),
                ('created_by', models.ForeignKey(help_text='Usuario que crea el objeto', on_delete=django.db.models.deletion.CASCADE, related_name='order_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='customer who made the order', on_delete=django.db.models.deletion.CASCADE, to='invoice.Customer')),
                ('deleted_by', models.ForeignKey(help_text='Usuario que elimina el objeto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Usuario que actualiza el objeto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Fecha de actualizacion', null=True)),
                ('deleted_date', models.DateTimeField(help_text='Fecha de eliminacion', null=True)),
                ('state', django_enumfield.db.fields.EnumField(default=1, enum=utils.django.db.models.State)),
                ('quantity', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(help_text='Usuario que crea el objeto', on_delete=django.db.models.deletion.CASCADE, related_name='orderdetail_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(help_text='Usuario que elimina el objeto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderdetail_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Fecha de actualizacion', null=True)),
                ('deleted_date', models.DateTimeField(help_text='Fecha de eliminacion', null=True)),
                ('state', django_enumfield.db.fields.EnumField(default=1, enum=utils.django.db.models.State)),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('product_description', models.TextField()),
                ('created_by', models.ForeignKey(help_text='Usuario que crea el objeto', on_delete=django.db.models.deletion.CASCADE, related_name='product_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(help_text='Usuario que elimina el objeto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Usuario que actualiza el objeto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Product'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='updated_by',
            field=models.ForeignKey(help_text='Usuario que actualiza el objeto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderdetail_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availableproduct',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Customer'),
        ),
        migrations.AddField(
            model_name='availableproduct',
            name='deleted_by',
            field=models.ForeignKey(help_text='Usuario que elimina el objeto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availableproduct_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availableproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Product'),
        ),
        migrations.AddField(
            model_name='availableproduct',
            name='updated_by',
            field=models.ForeignKey(help_text='Usuario que actualiza el objeto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availableproduct_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
